name: cipoc-avro-schema-registry
owner: sre
slack: pb-dumpster-land
configuration_opt_in_environments: true
pipeline:
  sandbox_cd_branch: main

staging:
  environment:
    RACK_ENV: staging
    RAILS_ENV: staging
production:
  environment:
    RACK_ENV: production
    RAILS_ENV: production
deployables: []

predeploy:
- dbmigrate

tests:
  primary:
  - name: avro-schema-registry
    build: .
    command: tail -f /dev/null
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: ezcater
      PORT: 3000
  services:
  - name: postgres
    image: postgres:14.4-alpine
    environment:
      POSTGRES_USER: ezcater
      POSTGRES_DB: avro-schema-registry_test
      POSTGRES_HOST_AUTH_METHOD: trust
  steps:
  - run:
      test: download cc-test-reporter
      command: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
        -o cc-test-reporter
  - run:
      test: cc-test-reporter permissions
      command: chmod +x ./cc-test-reporter
  - run:
      test: bundle config
      command: bundle config unset --local without
  - run:
      test: bundle
      command: bundle install
  - run:
      test: rubocop
      command: bundle exec rubocop
  - run:
      test: cc-before-build
      command: ./cc-test-reporter before-build
  - run:
      test: rspec
      command: bundle exec rspec --format documentation --format RspecJunitFormatter --out rspec.xml
  - run:
      test: cc-after-build
      command: ./cc-test-reporter after-build -t simplecov --exit-code $? || echo
        "Skipping Code Climate coverage upload"
